# Generated by Django 4.0.3 on 2022-03-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_current_bid_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bid_user_id',
        ),
    ]
