# Generated by Django 4.0.3 on 2022-03-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auction_current_bid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bidder_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bidder_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
