# Generated by Django 4.0.3 on 2022-03-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auction_current_bidder_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bidder_user_id',
        ),
    ]
