# Generated by Django 4.0.3 on 2022-03-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_auction_current_bidder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
